### ISSUE TITLE
ProximaNova-Reg-webfont.woff Bug Report

### ISSUE THREAD

**Issue by Veolinan** [Veolinan/leak#15]
There are no syntax errors in the provided code, so I will assume that you are looking for potential issues related to best practices or accessibility. Here are some suggestions:

1. It is recommended to include a `font-variant-ligatures: none;` declaration in the `body` rule to prevent potential issues with ligatures.
2. It is a good practice to include a `line-height` declaration in the `body` rule to ensure consistent line spacing throughout the document.
3. The `h6` rule sets the font size to `0.56em`, which may be too small for some users to read comfortably. Consider increasing the font size or using a larger font size for lower-level headings.
4. The `h1` to `h6` rules set the `margin-bottom` property to `0.25em`, which may be too small for some users to distinguish between headings and paragraphs. Consider increasing the margin size or using a larger margin for lower-level headings.
5. The `p` rule sets the `margin-bottom` property to `0.5em`, which may be too small for some users to distinguish between paragraphs. Consider increasing the margin size or using a larger margin for longer paragraphs.
6. It is a good practice to include `color` and `background-color` declarations in the `body` rule to ensure sufficient contrast for users with visual impairments.
7. It is recommended to include `text-rendering: optimizeLegibility;` in the `body` rule to improve the readability of text on some browsers.
8. It is a good practice to include `font-smooth: always;` in the `body` rule to improve the readability of text on some browsers.
9. It is recommended to include `-webkit-font-smoothing: antialiased;` in the `body` rule to improve the readability of text on some browsers.
10. It is a good practice to include `-moz-osx-font-smoothing: grayscale;` in the `body` rule to improve the readability of text on some browsers.

Here's an example of how the code could be modified to address these issues:

```css
@font-face {
  font-family: 'FwBTitl01';
  src: local('FwBTitl01'),
       url('FwBTitl01.ttf') format('truetype');
  font-style: normal;
  font-weight: normal;
}

body {
  font-family: 'FwBTitl01', sans-serif;
  font-variant-ligatures: none;
  line-height: 1.5;
  color: #333;
  background-color: #fff;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

h1 {
  font-size: 2em;
  margin-bottom: 1em;
}

h2 {
  font-size: 1.5em;
  margin-bottom: 1em;
}

h3 {
  font-size: 1.25em;
  margin-bottom: 1em;
}

h4 {
  font-size: 1em;
  margin-bottom: 1em;
}

h5 {
  font-size: 0.83em;
  margin-bottom: 1em;
}

h6 {
  font-size: 0.71em;
  margin-bottom: 1em;
}

p {
  margin-bottom: 1.5em;
}

```
